CREATE VIEW OVERALL_GRADES AS
SELECT
    s.STUDENT_ID,
    a.CLASS_ID,
    AVG(g.SCORE / a.MAXIMUM_SCORE * 100) AS PERCENTAGE,
    CASE
        WHEN AVG(g.SCORE / a.MAXIMUM_SCORE * 100) >= 90 THEN 'A'
        WHEN AVG(g.SCORE / a.MAXIMUM_SCORE * 100) >= 80 THEN 'B'
        WHEN AVG(g.SCORE / a.MAXIMUM_SCORE * 100) >= 70 THEN 'C'
        WHEN AVG(g.SCORE / a.MAXIMUM_SCORE * 100) >= 60 THEN 'D'
        ELSE 'F'
    END AS LETTER_GRADE
FROM 
    GRADES g
JOIN 
    ASSIGNMENTS a ON g.ASSIGNMENT_ID = a.ID
JOIN 
    STUDENT_CLASSES s ON g.STUDENT_ID = s.STUDENT_ID AND a.CLASS_ID = s.CLASS_ID
GROUP BY 
    s.STUDENT_ID, a.CLASS_ID;
