CREATE TABLE IF NOT EXISTS STUDENT_CLASSES (
    STUDENT_ID INTEGER NOT NULL,
    CLASS_ID INTEGER NOT NULL,
    PRIMARY KEY (STUDENT_ID, CLASS_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSES (ID) ON DELETE CASCADE
);
