CREATE TRIGGER CHECK_SCORE_MAX
BEFORE INSERT ON GRADES
FOR EACH ROW
  WHEN NEW.SCORE > (SELECT MAXIMUM_SCORE FROM ASSIGNMENTS WHERE ID = NEW.ASSIGNMENT_ID)
BEGIN
  SELECT RAISE(ABORT, 'Score cannot exceed the assignment maximum score');
END;
