CREATE TABLE IF NOT EXISTS ASSIGNMENTS (
    ID INTEGER PRIMARY KEY,
    CLASS_ID INTEGER NOT NULL,
    ASSIGNMENT_NAME TEXT NOT NULL,
    ASSIGNMENT_TYPE TEXT NOT NULL CHECK (
        ASSIGNMENT_TYPE IN ('Homework', 'Test')
    ),
    MAXIMUM_SCORE REAL NOT NULL,
    DUE_DATE TIMESTAMP,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSES (ID) ON DELETE CASCADE
);
