CREATE TABLE IF NOT EXISTS GRADES (
    STUDENT_ID INTEGER NOT NULL,
    ASSIGNMENT_ID INTEGER NOT NULL,
    SCORE REAL NOT NULL CHECK (SCORE >= 0),
    PRIMARY KEY (STUDENT_ID, ASSIGNMENT_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENTS (ID) ON DELETE CASCADE
);
